### ISSUE TITLE
Misleading: NOTICE:  database "fred11" does not exist, skipping

### ISSUE THREAD

**Issue by afswarm** [swarm64/tpc-toolkit#44]
I got this message when loading data into new database. I hadn't created the database in advance because the documentation gave me the impression (correctly) that it would create the database for me before inserting the data.
This message during the loading made me think that perhaps the database was not created. Maybe we could change "skipping" to "creating" if that is what it's going to do.

**Comment by sdressler** [comment]
Nothing we can do about. That comes from PostgreSQL and is caused by "DROP DATABASE ... IF EXISTS".
